name: caipoappv0
description: "flomad_caipo"
publish_to: 'none' # Not published to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0" # Specify the Dart SDK version constraint

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.4
  provider: ^6.1.2
  dialogflow_flutter: ^1.0.0
  file_picker: ^8.1.6
  speech_to_text: ^7.0.0
  http: ^0.13.3
  googleapis_auth: ^1.4.1
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
  #   - .env
